name: Build

on: [push]

jobs:
  build-on-windows:
    name: Build on Windows
    runs-on: windows-2019
    steps:
       
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1.5.0
      with:
        version: 3.1.x

    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Setup MSBuild.exe
      uses: microsoft/Setup-MSBuild@v1

    - name: Build Project
      run: |
        cd RimCI
        dotnet build
   #     msbuild RimCI.csproj -restore
        
  build-on-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Build Project
      run: |
        cd RimCI
        msbuild -t:restore
        msbuild

  build-on-mac:
    name: Build on MacOS
    runs-on: macOS-10.14
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Build Project
      run: |
        cd RimCI
        msbuild -t:restore
        msbuild
